CREATE TABLE OFFICER (
    OFFICER_NUM INT PRIMARY KEY,
    PHONE_NUM VARCHAR(15),
    GENDER CHAR(1),
    NAME VARCHAR(100),
    CERTIFICATION_NUM VARCHAR(20),
    ADDRESS VARCHAR(100),
    COUNTY VARCHAR(50),
    SCHEDULE VARCHAR(50),
    SUP_OFFICER_NUM INT
);

CREATE TABLE CASE_TABLE (
    CASE_ID INT NOT NULL,
    TIME TIMESTAMP,
    ISSUE VARCHAR(100) NOT NULL,
    CASE_STATUS VARCHAR(20),
    INVOLVED_PARTIES VARCHAR(200),
    LOCATION VARCHAR(100),
    OFFICER_NUM INT,
    FOREIGN KEY (OFFICER_NUM) REFERENCES OFFICER (OFFICER_NUM),
    PRIMARY KEY (CASE_ID, ISSUE)
);

CREATE TABLE CASE_FILE (
    CASE_FILE VARCHAR(100) PRIMARY KEY,
    SUSPECT VARCHAR(100),
    DOCUMENT_DETAILS VARCHAR(200),
    DOCUMENTATION_ID INT,
    CASE_ID INT,
    ISSUE VARCHAR(100),
    OFFICER_NUM INT,
    FOREIGN KEY (CASE_ID, ISSUE) REFERENCES CASE_TABLE (CASE_ID, ISSUE),
    FOREIGN KEY (OFFICER_NUM) REFERENCES OFFICER (OFFICER_NUM)
);	

CREATE TABLE CASE_FILE_DOC_DETAILS (
    DOC_DETAILS VARCHAR(200) PRIMARY KEY,
    DOC_TYPE VARCHAR(50),
    CASE_ID INT,
    ISSUE VARCHAR(100),
    OFFICER_NUM INT,
    FOREIGN KEY (CASE_ID, ISSUE) REFERENCES CASE_TABLE (CASE_ID, ISSUE),
    FOREIGN KEY (OFFICER_NUM) REFERENCES OFFICER (OFFICER_NUM)
);

CREATE TABLE CASE_FILE_SUSPECT (
    SUS_ID INT PRIMARY KEY,
    SUSPECT VARCHAR(100),
    AGE INT,
    FIRST_NAME VARCHAR(50),
    RECORD VARCHAR(100),
    LAST_NAME VARCHAR(50),
    MIDDLE_INIT CHAR(1),
    CASE_ID INT,
    ISSUE VARCHAR(100),
    OFFICER_NUM INT,
    FOREIGN KEY (CASE_ID, ISSUE) REFERENCES CASE_TABLE (CASE_ID, ISSUE),
    FOREIGN KEY (OFFICER_NUM) REFERENCES OFFICER (OFFICER_NUM)
);

CREATE TABLE CASE_INVOLVED_PARTIES (
    INVOLVED_PARTIES VARCHAR(200) PRIMARY KEY,
    VICTIMS VARCHAR(200),
    SUSPECTS VARCHAR(200),
    CASE_ID INT,
    ISSUE VARCHAR(100),
    OFFICER_NUM INT,
    FOREIGN KEY (CASE_ID, ISSUE) REFERENCES CASE_TABLE (CASE_ID, ISSUE),
    FOREIGN KEY (OFFICER_NUM) REFERENCES OFFICER (OFFICER_NUM)
);

CREATE TABLE CASE_LOCATION (
    LOCATION VARCHAR(100) PRIMARY KEY,
    COUNTY VARCHAR(50),
    STREET_ADDRESS VARCHAR(200),
    ZIP_CODE VARCHAR(10),
    BUILDING_NUM VARCHAR(20),
    COORDINATES VARCHAR(50),
    OFFICER_NUM INT,
    CASE_ID INT,
    ISSUE VARCHAR(100),
    FOREIGN KEY (OFFICER_NUM) REFERENCES OFFICER (OFFICER_NUM),
    FOREIGN KEY (CASE_ID, ISSUE) REFERENCES CASE_TABLE (CASE_ID, ISSUE)
);

CREATE TABLE COURT (
    COURT_ID INT PRIMARY KEY,
    COURT_OUTCOME VARCHAR(100),
    SCHEDULED_CASES VARCHAR(200),
    ASSOCIATED_DOCS VARCHAR(200),
    COURT_DATE DATE,
    OFFICER_NUM INT,
    FOREIGN KEY (OFFICER_NUM) REFERENCES OFFICER (OFFICER_NUM)
);

CREATE TABLE COURT_DATE (
    COURT_DATE DATE PRIMARY KEY,
    OFFICER_NUM INT,
    FOREIGN KEY (OFFICER_NUM) REFERENCES OFFICER (OFFICER_NUM)
);

CREATE TABLE EVIDENCE (
    EVIDENCE_ID INT PRIMARY KEY,
    EVIDENCE VARCHAR(100),
    CASE_ID INT,
    EVIDENCE_DETAILS VARCHAR(200),
    ISSUE VARCHAR(100),
    OFFICER_NUM INT,
    FOREIGN KEY (CASE_ID, ISSUE) REFERENCES CASE_TABLE (CASE_ID, ISSUE),
    FOREIGN KEY (OFFICER_NUM) REFERENCES OFFICER (OFFICER_NUM)
);

CREATE TABLE EVIDENCE_DETAILS (
    EVIDENCE_DETAILS VARCHAR(100) PRIMARY KEY,
    STORAGE_LOC VARCHAR(100),
    DESCRIPTION VARCHAR(200),
    FOUND_LOC VARCHAR(100),
    FINDING_OFFICER VARCHAR(100),
    CASE_ID INT,
    ISSUE VARCHAR(100),
    OFFICER_NUM INT,
    FOREIGN KEY (CASE_ID, ISSUE) REFERENCES CASE_TABLE (CASE_ID, ISSUE),
    FOREIGN KEY (OFFICER_NUM) REFERENCES OFFICER (OFFICER_NUM)
);

CREATE TABLE LOGISTICS (
    LOGISTICS_ID INT PRIMARY KEY,
    LIST_OF_VEHICLE_DETAILS VARCHAR(200),
    LIST_OF_SUPPLY_DETAILS VARCHAR(200),
    LIST_OF_EQUIPMENT_DETAILS VARCHAR(200),
    OFFICER_NUM INT,
    FOREIGN KEY (OFFICER_NUM) REFERENCES OFFICER (OFFICER_NUM)
);

CREATE TABLE MAKE (
    MAKE VARCHAR(50) PRIMARY KEY,
    BRAND VARCHAR(50),
    COLOR VARCHAR(50)
);

CREATE TABLE OFFICER_ADDRESS (
    ADDRESS VARCHAR(100) PRIMARY KEY,
    HOUSE_NUM VARCHAR(10),
    STREET_NAME VARCHAR(100),
    ZIP_CODE VARCHAR(10),
    OFFICER_NUM INT,
    SUP_OFFICER_NUM INT,
    FOREIGN KEY (OFFICER_NUM) REFERENCES OFFICER (OFFICER_NUM)
);

CREATE TABLE OFFICER_NAME (
    NAME VARCHAR(100) PRIMARY KEY,
    FIRST_NAME VARCHAR(50),
    MIDDLE_INIT CHAR(1),
    LAST_NAME VARCHAR(50),
    OFFICER_NUM INT,
    SUP_OFFICER_NUM INT,
    FOREIGN KEY (OFFICER_NUM) REFERENCES OFFICER (OFFICER_NUM)
);

CREATE TABLE OFFICER_SCHEDULE (
    SCHEDULE VARCHAR(50),
    SHIFT VARCHAR(20),
    WEEKDAY VARCHAR(10),
    OFFICER_NUM INT,
    SUP_OFFICER_NUM INT,
    FOREIGN KEY (OFFICER_NUM) REFERENCES OFFICER (OFFICER_NUM)
);

CREATE TABLE SUPERVISOR (
    SUP_OFFICER_NUM INT PRIMARY KEY,
    SUP_GENDER CHAR(1),
    SUP_COUNTY VARCHAR(50),
    SUP_PHONE_NUM VARCHAR(15),
    SUP_CERTIFICATION VARCHAR(20),
    SUP_NAME VARCHAR(100),
    SUP_SCHEDULE VARCHAR(50),
    SUP_ADDRESS VARCHAR(100),
    OFFICER_NUM INT,
    FOREIGN KEY (OFFICER_NUM) REFERENCES OFFICER (OFFICER_NUM)
);

CREATE TABLE SUPERVISOR_ADDRESS (
    SUP_ADDRESS VARCHAR(100) PRIMARY KEY,
    SUP_HOUSE_NUM VARCHAR(10),
    SUP_STREET_NAME VARCHAR(100),
    SUP_ZIP_CODE VARCHAR(10),
    OFFICER_NUM INT,
    FOREIGN KEY (OFFICER_NUM) REFERENCES OFFICER (OFFICER_NUM)
);

CREATE TABLE SUPERVISOR_NAME (
    SUP_NAME VARCHAR(100) PRIMARY KEY,
    SUP_FIRST_NAME VARCHAR(50),
    SUP_MIDDLE_INIT CHAR(1),
    SUP_LAST_NAME VARCHAR(50),
    OFFICER_NUM INT,
    FOREIGN KEY (OFFICER_NUM) REFERENCES OFFICER (OFFICER_NUM)
);

CREATE TABLE SUPERVISOR_SCHEDULE (
    SUP_SCHEDULE VARCHAR(50) PRIMARY KEY,
    SUP_SHIFT VARCHAR(50),
    SUP_WEEKDAY VARCHAR(50),
    OFFICER_NUM INT,
    FOREIGN KEY (OFFICER_NUM) REFERENCES OFFICER (OFFICER_NUM)
);

CREATE TABLE VEHICLE (
    VIN VARCHAR(17) PRIMARY KEY,
    AVAILABILITY VARCHAR(20),
    MODEL VARCHAR(50),
    MAKE VARCHAR(50),
    OFFICER_NUM INT,
    FOREIGN KEY (OFFICER_NUM) REFERENCES OFFICER (OFFICER_NUM)
);

CREATE TABLE WEAPON (
    SERIAL_NUM VARCHAR(50) PRIMARY KEY,
    TYPE VARCHAR(50),
    MAINTENANCE VARCHAR(100),
    AVAILABILITY VARCHAR(20),
    OFFICER_NUM INT,
    FOREIGN KEY (OFFICER_NUM) REFERENCES OFFICER (OFFICER_NUM)
);
